### PR TITLE
fix(pair_stable): precision mismatch on spread amount calc

### PR DESCRIPTION
**Pull request by P-Yevhenii**
#164

### CODE REVIEW

**Comment by romanovdavid** [comment]
Same problem in compute_offer_amount fn

**Comment by TheWineSeller** [comment]
Have to convert `spread_amount` precision to `ask_precision`.

`return_amount` and `spread_amount` must be same precision on `spread_assert` (when belief price is not given)

https://github.com/astroport-fi/astroport-core/blob/26440637463b122987ff4765e4ee54477f56d7f0/contracts/pair/src/contract.rs#L1145

**Comment by ShadoySV** [comment]
...and by the way, commission amount too

**Review by ShadoySV — APPROVED** [review]

**Comment by wedancedalot** [comment]
Closed in favor of #167

**Pull request closed without merging**
